
type Task = {
  id: number;
  title: string;
  completed: boolean;
  start: string| null;
  end: string| null;
  allday: boolean;
  date: string;
  repeat: boolean;
  list: string | null;
};


export const taskData: Task[] = [
  {
    id: 1,
    title: "Morning Jog",
    completed: false,
    start: "06:30",
    end: "07:00",
    allday: false,
    date: "2025-06-26",
    repeat: true,
    list: "Health",
  },
  {
    id: 2,
    title: "Team Standup Meeting",
    completed: true,
    start: "09:00",
    end: "09:30",
    allday: false,
    date: "2025-06-26",
    repeat: true,
    list: "Work",
  },
  {
    id: 3,
    title: "Write Blog Post",
    completed: false,
    start: "10:00",
    end: "11:30",
    allday: false,
    date: "2025-06-26",
    repeat: false,
    list: "Writing",
  },
  {
    id: 4,
    title: "Doctor Appointment",
    completed: false,
    start: "14:00",
    end: "15:00",
    allday: false,
    date: "2025-06-27",
    repeat: false,
    list: "Personal",
  },
  {
    id: 5,
    title: "Grocery Shopping",
    completed: false,
    start: "17:00",
    end: "18:00",
    allday: false,
    date: "2025-06-27",
    repeat: true,
    list: "Errands",
  },
  {
    id: 6,
    title: "Read a Book",
    completed: true,
    start: "20:00",
    end: "21:00",
    allday: false,
    date: "2025-06-27",
    repeat: false,
    list: "Hobby",
  },
  {
    id: 7,
    title: "Pay Bills",
    completed: false,
    start: "08:30",
    end: "09:00",
    allday: false,
    date: "2025-06-28",
    repeat: true,
    list: "Finance",
  },
  {
    id: 8,
    title: "Project Deadline",
    completed: false,
    start: "00:00",
    end: "23:59",
    allday: true,
    date: "2025-06-28",
    repeat: false,
    list: "Work",
  },
  {
    id: 9,
    title: "Lunch with Sarah",
    completed: false,
    start: "12:00",
    end: "13:30",
    allday: false,
    date: "2025-06-28",
    repeat: false,
    list: "Social",
  },
  {
    id: 10,
    title: "Watch a Movie",
    completed: true,
    start: "21:00",
    end: "23:00",
    allday: false,
    date: "2025-06-28",
    repeat: false,
    list: null,
  },
  {
    id: 11,
    title: "Gym Workout",
    completed: false,
    start: "07:30",
    end: "08:30",
    allday: false,
    date: "2025-06-29",
    repeat: true,
    list: "Health",
  },
  {
    id: 12,
    title: "Client Presentation",
    completed: false,
    start: "10:00",
    end: "11:00",
    allday: false,
    date: "2025-06-29",
    repeat: false,
    list: "Work",
  },
  {
    id: 13,
    title: "Weekly Review",
    completed: false,
    start: "16:00",
    end: "17:00",
    allday: false,
    date: "2025-06-29",
    repeat: true,
    list: "Planning",
  },
  {
    id: 14,
    title: "Volunteer Shift",
    completed: false,
    start: "18:00",
    end: "20:00",
    allday: false,
    date: "2025-06-29",
    repeat: false,
    list: "Community",
  },
  {
    id: 15,
    title: "Fix Website Bug",
    completed: false,
    start: "11:00",
    end: "13:00",
    allday: false,
    date: "2025-06-30",
    repeat: false,
    list: "Coding",
  },
  {
    id: 16,
    title: "Water Plants",
    completed: true,
    start: "08:00",
    end: "08:15",
    allday: false,
    date: "2025-06-30",
    repeat: true,
    list: "Home",
  },
  {
    id: 17,
    title: "Meditation",
    completed: true,
    start: "06:00",
    end: "06:20",
    allday: false,
    date: "2025-06-30",
    repeat: true,
    list: "Health",
  },
  {
    id: 18,
    title: "Call Parents",
    completed: false,
    start: "19:00",
    end: "19:30",
    allday: false,
    date: "2025-06-30",
    repeat: true,
    list: "Family",
  },
  {
    id: 19,
    title: "Write Journal",
    completed: true,
    start: "22:00",
    end: "22:15",
    allday: false,
    date: "2025-06-30",
    repeat: true,
    list: "Writing",
  },
  {
    id: 20,
    title: "All-day Hike",
    completed: false,
    start: "00:00",
    end: "23:59",
    allday: true,
    date: "2025-07-01",
    repeat: false,
    list: null,
  },
];
